# Generated by Django 4.2.3 on 2023-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
